### ISSUE TITLE
User Login and Frontend

### ISSUE THREAD

**Issue by Ryan-Huber1** [KellamA/322DineAutoProject#13]
**As a** customer
**I need** to be able to login 
**So that** I can look at what the restaurant has and order food
### Details and Assumptions
* There needs to be a "login system"

### Acceptance Criteria

```gherkin
Given I am in the login page
When I type in my email and password
And hit enter
Then I am sent to the homepage of the app/website
```

**Comment by shianwen** [comment]
Will complete in a later sprint when we have more time that we can dedicate to it.
